AWSTemplateFormatVersion: '2010-09-09'
Description: Strava Loader API Gateway with a Lambda Integrations
Resources:
  ApiGatewayDeployment:
    DependsOn: ApiGatewayMethod
    Properties:
      Description: Training Stats Lambda API Deployment
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Deployment
  ApiGatewayIamRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Sid: ''
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: lambda:*
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - StravaSubscriptionHandlerFunction
              - Arn
          Version: '2012-10-17'
        PolicyName: LambdaAccess
    Type: AWS::IAM::Role
  ApiGatewayMethod:
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        Credentials:
          Fn::GetAtt:
          - ApiGatewayIamRole
          - Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StravaSubscriptionHandlerFunction.Arn}/invocations
      OperationName: challenge
      ResourceId:
        Ref: ApiGatewayResource
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Method
  ApiGatewayModel:
    Properties:
      ContentType: application/json
      RestApiId:
        Ref: ApiGatewayRestApi
      Schema: {}
    Type: AWS::ApiGateway::Model
  ApiGatewayResource:
    Properties:
      ParentId:
        Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId
      PathPart: challenge
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Resource
  ApiGatewayRestApi:
    Properties:
      ApiKeySourceType: HEADER
      Description: Strava Loader API Gateway with a Lambda Integration
      EndpointConfiguration:
        Types:
        - EDGE
      Name: strava-integration-api
    Type: AWS::ApiGateway::RestApi
  ApiGatewayStage:
    Properties:
      DeploymentId:
        Ref: ApiGatewayDeployment
      Description: Training Stats Lambda API Stage V1
      RestApiId:
        Ref: ApiGatewayRestApi
      StageName: v1
    Type: AWS::ApiGateway::Stage
  LambdaStravaSubHandlerRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
    Type: AWS::IAM::Role
  StravaSubscriptionHandlerFunction:
    Properties:
      CodeUri: s3://training-stats/ecea549453d1c4f4c19b5c66a98ab23e
      Description: Strava Webhook Subscription Lambda function
      FunctionName: strava-sub-handler
      Handler: strava-sub-handler.lambda_handler
      MemorySize: 256
      Role:
        Fn::GetAtt:
        - LambdaStravaSubHandlerRole
        - Arn
      Runtime: python3.8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
